### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Eli-Black-Work** [Andarist/use-latest#2]
Hello 🙂

Can you please add a LICENSE file to this repository?

**Comment by mino-txa** [comment]
If based on the MIT license, a LICENSE file is required to use this package.
Could you please prepare it for us?

The MIT license requires a Copyright statement, so the following original license page is not appropriate
　https://opensource.org/license/mit/

**Comment by Andarist** [comment]
If you care about this - I accept PRs.

**Comment by mino-txa** [comment]
Yes, I do.
Please create.

**Comment by Eli-Black-Work** [comment]
@mino-txa, He's saying that he'd like you to create a pull request with the LICENSE file, and then he'll merge it 🙂

**Comment by mino-txa** [comment]
I understand.

**Comment by mino-txa** [comment]
Can Mr. Bosch create it?

**Comment by Eli-Black-Work** [comment]
Sadly, no... or at least not easily 😆  In order for me to contribute to an open source project, I need to get approval from my company, and I'm not yet familiar with the approval process.

Are you allowed to create one? If so, I could try to show you how to create a pull request like this 🙂

**Comment by mino-txa** [comment]
create pull request. #5

**Comment by Eli-Black-Work** [comment]
@mino-txa Wow, thank you! 🙂

I found a couple of strange typos in the LICENSE file. Not sure what happened there, lol 😆

**Comment by Eli-Black-Work** [comment]
Thanks again, @mino-txa 🙂
